#WALMART ANALYSIS--------------------------------------------------------------------------------------------------------------------------------
#INSTALL PACKAGES ----------------------
install.packages("tidyverse") #for cleaning, preparation and graphing
install.packages("lubridate") #dealing with dates in time-series analysis
library("tidyverse")
library("lubridate")


#IMPORT RAW DATA AS DATAFRAME
raw_data<-read.csv('raw_data/Walmart Dataset.csv', stringsAsFactors = FALSE)

#OVERVIEW OF DATA -------------------------
raw_data2<-raw_data %>% 
  mutate(across(where(is.character),as.factor))
str(raw_data2)
summary(raw_data2)

#DATA CLEANING AND PRE-PROCESSING---------------------
#REMOVE DUPLICATE ROWS
data <- raw_data[!duplicated(raw_data),] #returns  true for unique rows, false otherwise an keeps unique observations

# CHECK FOR MISSING VALUES ---------------------------------------------
colSums(is.na(data))

#IMPUTE MISSING VALUES------------------------------------------------------------------------------------------------------------
for (col in names(data)) {
  if (is.numeric(data[[col]])) {
    data[[col]][is.na(data[[col]])] <- median(data[[col]], na.rm = TRUE)
  }
} #replaces any NAs in column with median of column 

#CONVERT DATE COLUMNS FROM STRINGS TO DATE TYPES----------------------------------------------------------------------------------
data$Order.Date<-as.Date(data$Order.Date, format="%m/%d/%y") #small "y" since date is 2 numbers long
data$Ship.Date<-as.Date(data$Ship.Date, format="%m/%d/%y")
str(data) #checking if conversion worked 

#TRIM MISSING 
for (col in names(data)) {
  if (is.character(data[[col]])) {
    data[[col]] <- trimws(data[[col]])
  }
} #removes beginning or trailing white space to allow for consistent data format

#VISUALISATIONS --------------------------------------------------------------------------------------------------------------
#CATEGORICAL ANALYSIS------------------------------------------------------------------------------------------------
#Frequency of Shipping modes: Bar Chart
ggplot(data, aes(x = Ship.Mode))+
  geom_bar(fill="salmon1")+
  labs(title= "Frequency of Each Shipping Mode", 
       x= "Shipping mode",
       y="Number of shipments")
----------------------------------------------------------------
#Profit Generated By Region: Bar Chart
profit_by_region<-data %>% 
  group_by(Region) %>% 
  summarise(Total_profit= sum(Profit)) #calculating and assigning grouped total profits to dataframe 

ggplot(profit_by_region, aes(x = Total_profit, y = Region, fill= Region))+
  geom_col()+
  labs(title =" Total Profit Per Region",
       x = "Total profit",
       y = "Region")+
  scale_fill_manual(values= 
                      c("Central"="peachpuff",
                        "East"="indianred",
                        "South"="maroon",
                        "West"="mistyrose"))+
  scale_x_continuous(labels = scales::comma)
----------------------------------------------------------------
#Frequncy of Sales By Segment: Bar Chart
ggplot(data, aes(x = Segment)) +
  geom_bar(fill = "indianred") +
  coord_flip() +
  labs(title = "Count of Products by Segment", x = "Segment", y = "Count")

#BIVARIATE ANALYSIS--------------------------------------------------------------------------------------------------------
#Discounts vs Sales generated: Sactterplot 
#Numeric vs Numeric analysis
ggplot(data, aes(x = Sales, y = Profit)) +
  geom_point(alpha = 0.6, color = "darkred") +
  labs(title = "Sales vs Profit", x = "Sales", y = "Profit")
----------------------------------------------------------------
#Region vs Sales: Boxplot
#Numeric vs Categorical analysis
ggplot(data, aes(x = Region, y = Sales)) +
  geom_boxplot(fill = "mistyrose3") +
  labs(title = "Sales by Region", 
       x = "Region", 
       y = "Sales")+
  theme_minimal()

#TIME-SERIES ANALYSIS---------------------------------------------------------------------------------------------------------
#Profit over time (with trendline): Line chart  
time_series_1<-data %>% 
mutate(Yearmonth= floor_date(Order.Date, unit="month")) %>% 
group_by(Yearmonth) %>% 
  summarise(Total_profit= sum(Profit)) #groups profit by month and year and finds total profit of the month in that year 


ggplot(time_series_1, aes(x=Yearmonth, y= Total_profit))+
  geom_line(colour="chartreuse4") +
  labs(title = "Walmart Profit Growth Over Time",
       x = "Year ",
       y = "Total profit") +
  theme_minimal() +
  geom_smooth(method=lm, colour="salmon", se= FALSE)
----------------------------------------------------------------
#Quantity sold over time by segment: Line chart
time_series_3<-data %>% 
  mutate(Yearmonth= floor_date(Order.Date, unit="month")) %>% 
  group_by(Yearmonth, Segment) %>% 
  summarise(Total_quantity_sold= sum(Quantity)) 

ggplot(time_series_3, aes(x=Yearmonth, y= Total_quantity_sold,colour=Segment))+
  geom_line() +
  labs(title = "Quantity Sold Over Time By Segment",
       x = "Years",
       y = "Quantity sold") +
  scale_color_brewer(palette="Dark2")+
  theme_minimal()
#------------------------------------------------------------------------------------------------------------------ 
